pore_size+symmetry-MolAIR_End2End: # experiment id
  Agent:
    type: RND
    n_steps: 128
    epoch: 6
    seq_len: 75
    seq_mini_batch_size: 16
    gamma: 1.0
    nonepi_adv_coef: 1.0
  CountIntReward:
    crwd_coef: 0.01
  Env:
    pore_size_coef: 0.25
    symmetry_coef: 0.75
    max_str_len: 128
#    init_selfies: [
#
#    ]
  Train:
    num_envs: 64 # 64
    seed: 23
    total_time_steps: 10000
    summary_freq: 1000
    agent_save_freq: 5000
    num_inference_envs: 32 # 32
    n_inference_episodes: 1000
    lr: 1.0e-4
    device: cuda
    refset_path: data/raw/experts_merged.smi
    pretrained_path: # TODO
  Inference:
    num_envs: 64
    n_episodes: 10000
    seed: 23
    device: cuda
    ckpt: best
  Pretrain:
    dataset_path: modules/Mol-AIR/data/smiles.txt # older Chembl
    epoch: 50
    batch_size: 1024
    lr: 1.0e-3
    device: cuda
    seed: 23
    save_agent: false